---
name: galaxy

"on":
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  galaxy:
    runs-on: ubuntu-latest

    steps:
      - name: Update gitboard
        uses: gitboard-io/gitboard-action@main
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.GITBOARD_USERNAME }}
          key: ${{ secrets.GITBOARD_KEY }}

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Galaxy upload
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_TOKEN }}

...
