---
name: general

"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Role linting
        uses: actionhippie/ansible-later@v1

  testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        scenario:
          - default

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
          cache: pip

      - name: Install dependencies
        run: pip3 install docker ansible molecule molecule-plugins[docker]

      - name: Molecule tests
        run: molecule test --scenario-name ${{ matrix.scenario }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"

...
