---
name: general

"on":
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Update gitboard
        uses: gitboard-io/gitboard-action@main
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.GITBOARD_USERNAME }}
          key: ${{ secrets.GITBOARD_KEY }}

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Role linting
        uses: actionhippie/ansible-later@v1

  testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        scenario:
          - default

    steps:
      - name: Update gitboard
        uses: gitboard-io/gitboard-action@main
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.GITBOARD_USERNAME }}
          key: ${{ secrets.GITBOARD_KEY }}

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip3 install docker pytest-testinfra ansible molecule molecule-plugins[docker]

      - name: Molecule tests
        run: molecule test --scenario-name ${{ matrix.scenario }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"

...
