---
name: readme

"on":
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - name: Update gitboard
        uses: gitboard-io/gitboard-action@main
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.GITBOARD_USERNAME }}
          key: ${{ secrets.GITBOARD_KEY }}

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Generate readme
        uses: actionhippie/ansible-doctor@v1
        with:
          force: true
          verbose: true

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: README.md
          message: "docs: automated readme update [skip ci]"
          push: true
          commit: --signoff

...
